# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Swift
      uses: SwiftyLab/setup-swift@latest
    
    - name: Debug Build
      run: swift build -v -c debug
    - name: Run tests
      run: swift test -v -c debug

    - name: Release Build
      run: swift build -v -c release
    - name: Run tests
      run: swift test -v -c release
